// final List<PresetGroup> _presetGroups = [
//   PresetGroup(
//     groupName: "[VRWARE StoryCoding] 앨리스",
//     presets: [
//       Preset(
//         name: "1스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': "NUM_2"},
//           {'id': 'MOVE', 'param': "DIR_RIGHT"},
//           {'id': 'MOVE', 'param': "NUM_2"},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "1스테이지, 스텝 2",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', "param": "NUM_3"},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', "param": "DIR_RIGHT"},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', "param": "DIR_LEFT"},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "1스테이지, 스텝 3",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_2'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'MOVE', 'param': 'NUN_2'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "2스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_6'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "2스테이지, 스텝 2",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_3'},
//           {'id': 'MOVE', 'param': 'NUM_3'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'CLOSE'},
//           {'id': 'MOVE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "3스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_2'},
//           {'id': 'MOVE', 'param': 'NUM_3'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'CLOSE'},
//           {'id': 'MOVE', 'param': 'NUM_3'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "4스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_6'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'MOVE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "4스테이지, 스텝 2",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'FUNCTION'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'PLAY'},
//         ],
//         functionBlocks: [
//           {'id': 'REPEAT', 'param': 'NUM_3'},
//           {'id': 'MOVE'},
//           {'id': 'IF', 'param': 'SENSOR_FLOOR'},
//           {'id': 'LED_ON', 'param': 'NUM_2'},
//           {'id': 'CLOSE'},
//           {'id': 'CLOSE'},
//         ],
//       ),
//       Preset(
//         name: "5스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_2'},
//           {'id': 'MOVE', 'param': 'NUM_2'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "5스테이지, 스텝 2",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_3'},
//           {'id': 'REPEAT', 'param': 'NUM_2'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'MOVE', 'param': 'NUM_2'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "5스테이지, 스텝 3",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_3'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "5스테이지, 스텝 4",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_4'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//     ],
//   ),
//   PresetGroup(
//     groupName: "[VRWARE StroyCoding] 인어공주",
//     presets: [
//       Preset(
//         name: "1스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_2'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'MOVE', 'param': 'NUM_3'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "1스테이지, 스텝 2",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_3'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "1스테이지, 스텝 3",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_3'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'MOVE', 'param': 'NUM_3'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "2스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_4'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'MOVE'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "2스테이지, 스텝 2",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_4'},
//           {'id': 'REPEAT', 'param': 'NUM_2'},
//           {'id': 'MOVE', 'param': 'DIR_LEFT'},
//           {'id': 'MOVE', 'param': 'NUM_4'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "2스테이지, 스텝 3",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'REPEAT', 'param': 'NUM_3'},
//           {'id': 'MOVE', 'param': 'NUM_5'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "3스테이지, 스텝 1",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE', 'param': 'NUM_4'},
//           {'id': 'MOVE', 'param': 'DIR_RIGHT'},
//           {'id': 'MOVE', 'param': 'NUM_2'},
//           {'id': 'PLAY'},
//         ],
//       ),
//       Preset(
//         name: "3스테이지, 스텝 2",
//         blocks: [
//           {'id': 'START'},
//           {'id': 'MOVE'},
//           {
//             'id': 'REPEAT',
//             'param': 'DIAL',
//             'dialInput': '10',
//             'isDecimal': false,
//           },
//           {'id': 'IF', 'param': 'SENSOR_FRONT'},
//           {'id': 'SOUND', 'param': 'NUM_RANDOM'},
//           {'id': 'ELSE'},
//           {'id': 'MOVE', 'param': 'NUM_2'},
//           {'id': 'CLOSE'},
//           {'id': 'CLOSE'},
//           {'id': 'PLAY'},
//         ],
//       ),
//     ],
//   ),
// ];
